### ISSUE TITLE
Dimming on scroll

### ISSUE THREAD

**Issue by Urkman** [bazospa/giphy_get#14]
When I scroll through the list, it dims the screen from time to time.
Seems to be the case when I loads more results...

Looks not so nice :(

**Comment by Brazol** [comment]
look like adding gaplessPlayback to network image fixes this issue. I created PR with the fix: https://github.com/bazospa/giphy_get/pull/15

**Comment by bazookon** [comment]
Thanks @Brazol merged

**Comment by Urkman** [comment]
Could you make a new release?
