### ISSUE TITLE
[Question] Using cache network image package

### ISSUE THREAD

**Issue by itssidhere** [bazospa/giphy_get#2]
I have a question. Why exactly is cached network image being used here as it will fill the cache without any way to clear that particular cache , also it adds a minimum 1.20.0 version restriction which is quiet unstable for now. I would propose to use extended_image or just no caching

**Comment by bazookon** [comment]
I use for speed up loading gif, but I'll try with extended_image, thanks i don't know this library. Could you make this PR?
