### ISSUE TITLE
Has anyone gotten approved for a Prod API key?

### ISSUE THREAD

**Issue by armandojimenez** [bazospa/giphy_get#7]
I see in the guidelines than one must show the Powered by Giphy logo,

has anyone been able to get a key approved?

from Giphy Docs:

Attribution
We require all apps that use GIPHY API to conspicuously display "Powered By GIPHY" attribution marks where the API is utilized (see SDK attribution guide here). You can find approved official logo marks here

https://mailchi.mp/0762226d308c/important-updates-for-your-giphy-integration.

**Comment by TramPamPam** [comment]
@armandojimenez hi, I believe it's not an issue for this library


Just add this logo that they mention over the widget where you use picked gif. It worked for me ;)

**Comment by armandojimenez** [comment]
@TramPamPam Thanks! I was just approved for a prod key using this package, and I only had the powered by GiPHY attribution. also thanks for fixing the errors.
